
export const dateIdeas = [
      "Play ping pong",
      "Play tennis",
      "Candlelight dinner",
      "Take a scenic hike and have a picnic at the summit.",
      "Visit a local art gallery or museum.",
      "Have a movie night under the stars with a projector and blankets.",
      "Try a new restaurant and order something you've never had before.",
      "Take a cooking class together.",
      "Have a themed dinner night at home, like Italian or Mexican cuisine.",
      "Explore a nearby town or city you've never been to.",
      "Attend a live music or comedy show.",
      "Visit a botanical garden and enjoy the beautiful flora.",
      "Go horseback riding.",
      "Have a beach day with swimming, sunbathing, and beach games.",
      "Go ice skating or roller skating at a local rink.",
      "Take a scenic drive and have a picnic along the way.",
      "Try a new outdoor adventure activity, like zip-lining or rock climbing.",
      "Attend a local sports game or event.",
      "Explore a farmers' market and try local foods.",
      "Visit a historical site or landmark in your area.",
      "Have a DIY craft night and make something special together.",
      "Go on a bike ride through a scenic trail.",
      "Take a pottery or ceramics class.",
      "Visit a planetarium and stargaze together.",
      "Go to a local arcade and play games.",
      "Have a photo scavenger hunt in your city.",
      "Attend a themed costume party or event.",
      "Go on a hot air balloon ride for a unique perspective.",
      "Volunteer together at a local charity or organization.",
      "Take a scenic boat ride or cruise.",
      "Have a spa day at home with massages and relaxation.",
      "Explore a nearby national park or nature reserve.",
      "Find a free local concert to attend together",
      "Go clothes shopping together and pick out an outfit for each of you",
      "Go through old photo albums together",
      "Read old journal entries",
      "Go to a local coffee shop and try a new drink",
      "See what unique festivals are available in your area",
      "See what events the local conservation department offers",
      "Visit an indoor trampoline park and bounce around together.",
      "Go on a day trip to a nearby vineyard for wine tasting.",
      "Take a scenic train ride through picturesque landscapes.",
      "Explore a nearby botanical garden and have a photoshoot.",
      "Have a themed movie marathon night at home.",
      "Try geocaching together and go on a treasure hunt.",
      "Attend a local comedy improv show for lots of laughs.",
      "Take a dance class, like salsa or swing dancing.",
      "Visit an escape room and work together to solve puzzles.",
      "Go to a karaoke bar and sing your hearts out.",
      "Have a picnic in a local park and fly kites.",
      "Take a scenic sunset or sunrise photography expedition.",
      "Attend a food festival or street food fair in your area.",
      "Try indoor rock climbing at a climbing gym.",
      "Go to a drive-in movie theater for a nostalgic date night.",
      "Visit a local animal sanctuary or petting zoo.",
      "Take a scenic helicopter tour of your city or region.",
      "Attend a local theater production or musical.",
      "Go horseback riding on the beach at sunset.",
      "Visit an ice cream parlor and create your own sundaes.",
      "Try stand-up paddleboarding or kayaking on a serene lake.",
      "Go on a scenic bike ride through a forest or nature reserve.",
      "Visit a historic lighthouse and enjoy the view.",
      "Take a scenic ferry ride to a nearby island or coastal town.",
      "Attend a paint night at a local studio.",
      "Explore a corn maze or go pumpkin picking in the fall.",
      "Have a board game night with your favorite games.",
      "Take a day trip to a nearby hot spring for relaxation.",
      "Visit a local science museum and engage in hands-on exhibits.",
      "Take a pottery wheel throwing class.",
      "Attend a local minor league baseball game.",
      "Go on a photography scavenger hunt in your city.",
      "Visit an indoor trampoline park and have a jumping competition.",
      "Go to a local botanical garden and have a picnic.",
      "Take a scenic helicopter tour of your city or region.",
      "Attend a local theater production or musical.",
      "Visit a historic lighthouse and enjoy the view.",
      "Take a scenic ferry ride to a nearby island or coastal town.",
      "Attend a paint night at a local studio.",
      "Explore a corn maze or go pumpkin picking in the fall.",
      "Have a board game night with your favorite games.",
      "Take a day trip to a nearby hot spring for relaxation.",
      "Go birdwatching in a nature preserve or bird sanctuary.",
      "Attend a local poetry reading or spoken word event.",
      "Have a DIY home improvement project day.",
      "Go horseback riding through a scenic forest trail.",
      "Visit a local farmers' market and cook a meal with fresh ingredients.",
      "Visit a butterfly garden and admire the colorful butterflies.",
      "Take a scenic train ride through the countryside.",
      "Go on a photography expedition to capture beautiful landscapes.",
      "Attend a stand-up comedy show and share some laughs.",
      "Explore a nearby historic district and learn about its history.",
      "Have a themed game night with board games, cards, and snacks.",
      "Visit a rooftop bar for cocktails and city views.",
      "Go on a night hike with flashlights to stargaze away from city lights.",
      "Try indoor skydiving for an exhilarating experience.",
      "Attend a book reading or author event at a local bookstore.",
      "Visit a local science center and participate in interactive exhibits.",
      "Take a scenic horse-drawn carriage ride through the city.",
      "Have a DIY home spa day with facials and relaxation.",
      "Go on a road trip to explore neighboring towns and landmarks.",
      "Take a dance class, such as salsa, tango, or ballroom.",
      "Visit a local comedy club for a night of humor and fun.",
      "Go on a paddleboat or canoe ride on a tranquil lake.",
      "Attend a live jazz or blues music performance.",
      "Visit a local historic cemetery and take a spooky tour.",
      "Have a picnic in a botanical garden or arboretum.",
      "Try indoor go-kart racing for some friendly competition.",
      "Go on a scenic horseback ride through rolling hills.",
      "Visit a local brewery and sample craft beers.",
      "Attend a local film festival and watch indie films.",
      "Explore a nearby nature trail and observe wildlife.",
      "Have a movie night with a marathon of your favorite films.",
      "Visit a local pottery studio and create ceramic art together.",
      "Go on a food truck tour and try different cuisines.",
      "Attend a live theater performance or musical.",
      "Take a scenic hot air balloon ride at sunrise or sunset.",
      "Visit a wildlife sanctuary or rehabilitation center.",
      "Have a picnic at a scenic overlook or hilltop.",
      "Try indoor rock climbing for an active date.",
      "Go on a brewery or distillery tour and tasting.",
      "Visit an aquarium and learn about marine life.",
      "Have a themed costume night at home, complete with costumes.",
      "Attend a local outdoor concert or music festival.",
      "Go on a city bike tour to explore hidden gems.",
      "Visit a local botanical garden during a special event.",
      "Have a movie night with classic films and popcorn.",
      "Take a cooking class focused on a specific cuisine.",
      "Go on a scenic helicopter tour for breathtaking views.",
      "Visit a historic train station and explore its history.",
      "Have a picnic in a city park with a beautiful view.",
      "Try indoor mini-golf for a fun and lighthearted date.",
      "Go on a ghost tour of a haunted location in your area.",
      "Attend a local community theater production.",
      "Explore a nearby cave or underground attraction.",
      "Visit a local historical reenactment or Renaissance fair.",
      "Go on a wildlife safari or visit a zoo together.",
      "Have a day of water activities like kayaking, paddleboarding, and swimming.",
      "Attend a vintage or antique market for unique finds.",
      "Take a scenic helicopter tour over a nearby city or landscape.",
      "Explore a nearby cave or underground caverns.",
      "Go on a wine and cheese tasting tour at local vineyards.",
      "Have a day of kite flying at a beach or open field.",
      "Attend a cooking competition or culinary event.",
      "Visit a planetarium and explore the cosmos together.",
      "Have a day of cultural exploration by visiting ethnic neighborhoods and trying their cuisine.",
      "Go on a horse-drawn carriage ride through a historic district.",
      "Attend a local outdoor theater performance or Shakespeare in the Park.",
      "Visit a historic battlefield or Civil War reenactment.",
      "Have a DIY art day and create paintings or sculptures together.",
      "Take a pottery or ceramics class to create unique pieces.",
      "Go on a scenic helicopter tour over a nearby city or landscape.",
      "Visit a local botanical garden during a special seasonal event.",
      "Have a themed costume night at home, complete with costumes and role-playing.",
      "Attend a local outdoor concert or music festival in the park.",
      "Go on a city bike tour to explore hidden gems and neighborhoods.",
      "Visit a local pottery studio and create ceramic art together.",
      "Take a cooking class focused on a specific cuisine you both love.",
      "Attend a live theater performance or musical at a local venue.",
      "Have a picnic in a city park with a beautiful view.",
      "Explore a nearby cave or underground attraction.",
      "Visit a historic train station and explore its history.",
      "Go on a ghost tour of a haunted location in your area.",
      "Attend a local community theater production or play.",
      "Explore a nearby arboretum and learn about different tree species.",
      "Have a day of geocaching and treasure hunting in your area.",
      "Visit a local vintage arcade and play classic games.",
      "Go on a scenic paddleboat or canoe ride on a serene lake.",
      "Attend a local trivia night at a bar or restaurant.",
      "Explore a nearby sculpture garden or outdoor art installation.",
      "Have a themed 1980s or 1990s movie night at home.",
      "Go on a scenic hot air balloon ride at sunrise or sunset.",
      "Visit a local planetarium and stargaze together.",
      "Attend a local salsa dancing night and learn some moves.",
      "Have a day of roller skating at a local rink or roller disco.",
      "Go on a wildlife photography expedition in a nearby nature reserve.",
      "Visit a local food truck festival and sample a variety of cuisines.",
      "Attend a local symphony orchestra or classical music performance.",
      "Explore a nearby wildlife sanctuary or rehabilitation center.",
      "Have a day of fruit picking at a local orchard.",
      "Go on a scenic seaplane tour for a unique perspective.",
      "Visit a local historical mansion and take a guided tour.",
      "Attend a local comedy improv workshop or class together.",
      "Have a day of exploring quirky roadside attractions in your area.",
      "Go on a tandem bike ride through scenic routes.",
      "Visit a local roller derby match for an action-packed date.",
      "Attend a local circus or acrobatics show for a thrilling experience.",
      "Have a day of hiking and exploring caves in a national park.",
      "Go on a scenic riverboat cruise for a relaxing date.",
      "Visit a nearby farmer's market and shop for fresh produce.",
      "Attend a local craft fair and shop for handmade items.",
      "Have a day of indoor trampolining and dodgeball fun.",
      "Go on a wine and chocolate tasting tour at local wineries.",
      "Visit a nearby beach town and enjoy seafood by the ocean.",
      "Attend a local charity fundraiser or gala event.",
      "Have a day of visiting historic churches and cathedrals.",
      "Go on a scenic mountain biking adventure in the wilderness.",
      "Visit a local wildlife rehabilitation center and learn about conservation.",
      "Attend a local puppet show or marionette theater performance.",
      "Have a day of exploring antique shops and vintage stores.",
      "Go on a scenic horseback ride through mountain trails.",
      "Visit a local botanical garden during their annual flower festival.",
      "Attend a local film screening of a classic or indie movie.",
      "Have a day of birdwatching in a serene natural habitat.",
      "Go on a scenic horse-drawn carriage ride through a park.",
      "Have a day of indoor go-kart racing and competitive fun.",
      "Go on a wine and painting class to create your own art pieces.",
      "Visit a local wildlife refuge and spot native animals.",
      "Attend a local drag show or burlesque performance.",
      "Have a day of exploring local urban art and street murals.",
      "Go on a scenic river kayaking or canoeing adventure.",
      "Visit a nearby archaeological site and learn about ancient history.",
      "Attend a local carnival or fair with rides and games.",
      "Have a day of exploring historic covered bridges in your area.",
      "Go on a chocolate factory tour and indulge in sweet treats.",
      "Visit a local arboretum and learn about diverse tree species.",
      "Attend a local carnival or amusement park for thrill rides.",
      "Have a day of exploring local gardens and horticultural displays.",
      "Go on a scenic paddleboarding adventure on a calm lake.",
      "Visit a local observatory and stargaze through telescopes.",
      "Attend a local car show or classic car exhibition.",
      "Have a day of exploring local caves and underground formations.",
      "Go on a scenic riverboat dinner cruise for a romantic evening.",
      "Visit a nearby wildlife preserve and watch for migratory birds.",
      "Attend a local roller derby match for a lively date night.",
      "Have a day of exploring local historic bridges and landmarks.",
      "Go on a pottery painting workshop and create personalized ceramics.",
      "Visit a local wildlife rehabilitation center and volunteer together.",
      "Attend a local outdoor Shakespeare in the Park performance.",
      "Have a day of exploring local historical landmarks and sites.",
      "Go on a scenic mountain biking excursion through rugged trails.",
      "Visit a local science center and participate in hands-on experiments.",
      "Attend a local ice skating show or figure skating exhibition.",
      "Have a day of wine and cheese tasting at a picturesque vineyard.",
      "Go on a fishing trip and try to catch your own dinner.",
      "Visit a local wildlife sanctuary and learn about endangered species.",
      "Go on a scenic gondola ride in a picturesque location.",
      "Attend a live taping of a TV show or talk show.",
      "Have a day of exploring quirky and unusual museums.",
      "Go on a scenic road trip along a famous scenic route.",
      "Visit a local botanical garden during a butterfly release event.",
      "Attend a local street food festival and indulge in international cuisine.",
      "Have a day of exploring local caves and underground caverns.",
      "Go on a scenic horseback ride through a forested trail.",
      "Visit a local wildlife refuge and observe native animals.",
      "Attend a local food and wine pairing event.",
      "Have a day of stand-up paddleboarding on a tranquil lake.",
      "Go on a scenic riverboat dinner cruise for a romantic evening.",
      "Visit a nearby wildlife sanctuary and volunteer together.",
      "Attend a local outdoor Shakespeare in the Park performance.",
      "Have a day of exploring local historical landmarks and sites.",
      "Go on a mountain biking adventure through scenic trails.",
      "Visit a local science center and participate in hands-on experiments.",
      "Attend a local ice skating show or figure skating exhibition.",
      "Go on a fishing trip and try to catch your own dinner.",
      "Visit a local wildlife sanctuary and learn about endangered species.",
      "Attend a local TED Talk event or intellectual discussion.",
      "Have a day of exploring local art galleries and studios.",
      "Go on a scenic river tubing adventure with calm waters.",
      "Visit a nearby historic fort or military reenactment.",
      "Attend a local film screening of a foreign or independent film.",
      "Have a day of exploring local wineries and vineyards.",
      "Go on a scenic hot air balloon ride at dawn or dusk.",
      "Visit a local food festival celebrating a specific cuisine.",
      "Attend a local stand-up comedy workshop or open mic night.",
      "Have a day of indoor rock climbing and bouldering.",
      "Go on a craft beer tasting tour at local breweries.",
      "Visit a local science museum and explore interactive exhibits.",
      "Attend a local dance performance or ballet show.",
      "Have a day of exploring historic lighthouses along the coast.",
      "Go on a scenic river kayaking adventure through gentle rapids.",
      "Visit a nearby national park and hike to a stunning viewpoint.",
      "Attend a local charity run or walk event together.",
      "Have a day of exploring local art installations and murals.",
      "Go on a scenic zip-lining adventure through a forest canopy.",
      "Visit a local observatory and stargaze through telescopes.",
      "Attend a local jazz festival or outdoor jazz concert.",
      "Have a day of exploring local farmers' markets and vendors.",
      "Go on a relaxing horse-drawn carriage ride through the city.",
      "Visit a local eco-park or nature center for outdoor activities.",
      "Attend a local flower festival or tulip festival.",
      "Have a day of exploring local historic theaters and venues.",
      "Go on a scenic waterfall hike and enjoy the natural beauty.",
      "Visit a local wildlife rehabilitation center and assist in care.",
      "Go on a scenic parasailing adventure over a pristine lake.",
      "Visit a local food truck rally and sample diverse cuisines.",
      "Attend a local community theater musical production.",
      "Have a day of exploring local nature trails and wildlife.",
      "Go on a tandem skydiving adventure for an adrenaline rush.",
      "Attend a local circus performance for a thrilling date.",
      "Have a day of geocaching and treasure hunting in the wilderness.",
      "Go on a scenic horseback ride along a scenic beach.",
      "Visit a local pottery studio and create clay masterpieces.",
      "Attend a local kite festival and fly colorful kites.",
      "Have a day of indoor trampolining and aerial acrobatics.",
      "Go on a scenic snowshoeing adventure in the winter.",
      "Visit a local bird sanctuary and observe various bird species.",
      "Attend a local charity gala or formal fundraising event.",
      "Have a day of exploring local historic cemeteries and tombstones.",
      "Go on a scenic ice fishing excursion in the winter.",
      "Visit a local glassblowing studio and create glass art together.",
      "Attend a local science fiction or fantasy convention.",
      "Have a day of exploring local urban gardens and green spaces.",
      "Go on a scenic snowmobile tour through snowy landscapes.",
      "Visit a local wildlife education center and learn about animals.",
      "Attend a local tango dance event and learn the dance together.",
      "Have a day of exploring local architectural landmarks.",
      "Go on a scenic cross-country skiing adventure in the winter.",
      "Visit a local marine aquarium and learn about sea life.",
      "Attend a local pet adoption event and consider adopting a pet.",
      "Have a day of exploring local historic covered bridges.",
      "Go on a scenic dog sledding adventure in the winter.",
      "Visit a local glass art gallery and admire unique glass sculptures.",
      "Attend a local circus skills workshop and try juggling and acrobatics.",
    ];
  
